spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-236-169-55.compute-1.amazonaws.com/dbi66s64uu9iq6?sslmode=require
    username: bzajoblemlblhm
    password: ba7aa32ab325cacaec3255e2340cb3651c8bc9e9cb60437347073433dd85d0b1

  mail:
    host: smtp.gmail.com
    port: 587
    username: my.clothes0702@gmail.com
    password: beycwsheoeetkjpn
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    
  
   