spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-156-121-142.compute-1.amazonaws.com/dueibdn4a3aq0?sslmode=require
    username: lmicnyxioaregd
    password: d5b51cc4067a4323ccd3d6a524730895af85675edc2521fb17aca67d2d4e1161

  mail:
    host: smtp.gmail.com
    port: 587
    username: my.clothes0702@gmail.com
    password: beycwsheoeetkjpn
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    
  
   